import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import Banner from "../../public/assets/banner.png";
import { useState } from "react";


import { produtosEntradas, filtrarProdutos, buscarProdutos } from "../service";

import Categorias from '../components/Categorias'
import CampoDeBusca from "../components/CampoDeBusca";
import Card from "../components/Cards";

export default function Home() {
  const [dadosFiltrados, setDadosFiltrados] = useState(produtosEntradas);
  const [textoBuscaDigitado, setTextoBuscaDigitado] = useState('');

  const [botaoClicado, setBotaoClicado] = useState('Entradas');

  const handleBusca = (textoDigitado) => {
    setTextoBuscaDigitado(textoDigitado);
    if(textoBuscaDigitado.length >= 3) {
      setDadosFiltrados(buscarProdutos(textoBuscaDigitado));
    } else if (botaoClicado){
      setDadosFiltrados(filtrarProdutos(botaoClicado))
    } else {
      setDadosFiltrados(produtosEntradas)
    }
  }
 
  const handleFiltro = (categoria) => {
    setDadosFiltrados(filtrarProdutos(categoria));
    setBotaoClicado(categoria);
    setTextoBuscaDigitado('');
  };

  return (
    <>
      <Head>
        <title>RESTAURANT</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
        
      </Head>

      <header className={styles.banner}>
        <Image src={Banner} />
        <div className={styles.banner_container_texto}>
          <h1>RESTAURANT</h1>
          <p>
            De pratos clássicos a criações surpreendentes, nosso cardápio é um
            requinte de sabores refinados
          </p>
        </div>
      </header>
      <main className={styles.container_principal}>
        <Categorias 
        handleFiltro={handleFiltro}
        botaoClicado={botaoClicado}
        />

        <CampoDeBusca 
        handleBusca={handleBusca}
        textoBuscaDigitado={textoBuscaDigitado}
        />

        <section className={styles.secao_cards}>
          <div>
            <h2>Cardápio</h2>
          </div>

          <div className={styles.container_cards}>
          {dadosFiltrados.map((produto) => (
            <Card key={produto.id} produto={produto} />
          ))}
          </div>
        </section>
      </main>
    </>
  );
}
